spring:
  application:
    name: monitor-app

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'

info:
  app:
    name: "Monitoring App"
    description: "Monitoring with Prometheus and Grafana"
    version: "1.0.0"
