scrape_configs:
  - job_name: 'monitor-app'
    metrics_path: '/actuator/prometheus'
    scrape_interval: '10s'
    static_configs:
      - targets: ['192.168.1.3:8080'] # TODO: put your own IP address here...